Setup react-frontend
Ibtisam34/Hello-world-front-end pull request #1
Opened 2023-04-10 15:34 UTC by Ibtisam34

- [ ] This exercise is going to have I  created a React front-end with a Rails back-end and connect them to display a random message.

2023-04-10 16:47 UTC, Gambit142 requested changes
Hi @Ibtisam34 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- Use of reducers, actions and `createAsyncThunk` ✔️ 
- It has `App` and `Greeting` component ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-04-10 16:47 UTC, Gambit142 commented on src/store.js
> +});
- [ ] You didn't create a store for your reducer. you need to create a store that holds the whole state tree of your application. It is through the store that components can connect to the application's state and change the state through the dispatch of actions. 👍

2023-04-10 16:47 UTC, Gambit142 commented on src/index.js
> +);
- [ ] When I start the application, the screen is blank. After creating the store, you need to connect to the store using the Provider component from redux. Kindly apply this change. 👍 😎

2023-04-11 04:41 UTC, andersonlebon approved these changes
## Hi @Ibtisam34 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-11 04:41 UTC, andersonlebon commented on README.md
> +> Describe your project in 1 or 2 sentences.
## [OPTIONAL]

- [ ] To make your readme file more professional I think is good that all readme template text descriptions are removed

2023-04-11 04:41 UTC, andersonlebon commented on README.md
> +> Give credit to everyone who inspired your codebase.
## [OPTIONAL]

- [ ] To make your readme file more professional I think is good that all readme template text descriptions are removed

2023-04-11 04:41 UTC, andersonlebon commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
## [OPTIONAL]
- [ ] To make your readme file more professional I think is good that all readme template text descriptions are removed

2023-04-11 04:55 UTC, merged